#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - btrfs-progs
  - python27-pip
  - sed
  - wget


runcmd:
  - pip install -U awscli boto3
  - cd /opt && wget https://aws-genomics-workflows.s3.amazonaws.com/artifacts/aws-ebs-autoscale.tgz && tar -xzf aws-ebs-autoscale.tgz
  - sh /opt/ebs-autoscale/install.sh /scratch 2>&1 > /var/log/intall-ebs-autoscale.log
